service: memory-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3001
    host: 0.0.0.0

functions:
  api:
    handler: src/index.handler
    events:
      - http:
          path: /{proxy+}
          method: any